version: '2'
services:
  clamav:
    build:
      context: clamav
  clamav-rest:
    build:
      context: clamav-rest
    links:
      - clamav:clamav-server
    environment:
      HOST: clamav-server
      PORT: 3310
    depends_on:
      - clamav
    ports:
      - 8080:8080
